version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: nest-docker-app
    ports:
      - '3002:3000'
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./:/app/
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_ROOT_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
  db:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_USER_PASSWORD=$DB_PASSWORD
    ports:
      - ${DB_DOCKER_PORT}:${DB_DOCKER_PORT}
    volumes:
      - './.mysql-data/db:/var/lib/mysql'
    networks:
      - backend


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '80:80'
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge